title: 패턴인식과 \n머신러닝
logo: /assets/img/logo.png
description: Study
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
